### ISSUE TITLE
Установить ROS2 и продемонстрировать его работу на библиотечных `demo_nodes_cpp talker` и `demo_nodes_py listener`.

### ISSUE THREAD

**Issue by danilasimanok** [moevm/mse1h2024-drones#10]

**Comment by danilasimanok** [comment]
Результат работы должен выглядеть так.
![image](https://github.com/moevm/mse1h2024-drones/assets/23316183/4ab53df3-1729-4bf3-a178-59c258831b4d)

**Comment by Cottoffey** [comment]
В общем, я пытался установить на windows, но оно не работает пока. 
Установка под linux выглядит проще. Может, перейду на линукс и повторю процесс.

**Comment by Cottoffey** [comment]
![изображение](https://github.com/moevm/mse1h2024-drones/assets/90787558/3bc18f42-4f79-4d0d-8c32-323d88f37703)

**Comment by avariiinaa** [comment]
![proof](https://github.com/moevm/mse1h2024-drones/assets/52382060/4ca16697-fcb2-4daa-87d1-b0af10822bb7)

**Comment by NguyenHai-LETI** [comment]
![Screenshot 2024-04-01 183239](https://github.com/moevm/mse1h2024-drones/assets/43198848/95d7e468-604d-4521-ac2d-0d75046d1d7b)
